// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TindeqTrainer.Infrastructure.Persistence;

#nullable disable

namespace TindeqTrainer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404125921_MoveRestToWorkoutProtocolItem")]
    partial class MoveRestToWorkoutProtocolItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.MaxWeightRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("LeftWeightKg")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RightWeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.ToTable("MaxWeightRecords");
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.RepeaterProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AudioCues")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CountdownBeeps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CountdownSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("HandSwitchSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepsPerSet")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RestSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("SetRestSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("WeightPercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("WorkSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RepeaterProtocols");

                    b.HasData(
                        new
                        {
                            Id = new Guid("664101f7-7dcd-4fb4-94f5-61e7f80c6ef0"),
                            AudioCues = true,
                            CountdownBeeps = true,
                            CountdownSeconds = 5.0,
                            HandSwitchSeconds = 30.0,
                            Name = "Max Repeaters 80%",
                            NumberOfSets = 1,
                            RepsPerSet = 6,
                            RestSeconds = 3.0,
                            SetRestSeconds = 0.0,
                            WeightPercentage = 80.0,
                            WorkSeconds = 7.0
                        },
                        new
                        {
                            Id = new Guid("2cf4e16b-c3a7-4dfa-8944-b1d6b2384f89"),
                            AudioCues = true,
                            CountdownBeeps = true,
                            CountdownSeconds = 5.0,
                            HandSwitchSeconds = 30.0,
                            Name = "Endurance 60%",
                            NumberOfSets = 1,
                            RepsPerSet = 10,
                            RestSeconds = 3.0,
                            SetRestSeconds = 0.0,
                            WeightPercentage = 60.0,
                            WorkSeconds = 7.0
                        },
                        new
                        {
                            Id = new Guid("d53a3ea5-d9bf-43a6-8ff8-e8f7c7f07f0a"),
                            AudioCues = true,
                            CountdownBeeps = true,
                            CountdownSeconds = 5.0,
                            HandSwitchSeconds = 30.0,
                            Name = "Short Power 90%",
                            NumberOfSets = 1,
                            RepsPerSet = 4,
                            RestSeconds = 5.0,
                            SetRestSeconds = 0.0,
                            WeightPercentage = 90.0,
                            WorkSeconds = 5.0
                        });
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.WorkoutProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutProtocols");
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.WorkoutProtocolItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepeaterProtocolId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RestAfterSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutProtocolId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepeaterProtocolId");

                    b.HasIndex("WorkoutProtocolId", "SortOrder")
                        .IsUnique();

                    b.ToTable("WorkoutProtocolItems");
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.WorkoutProtocolItem", b =>
                {
                    b.HasOne("TindeqTrainer.Domain.Entities.RepeaterProtocol", "RepeaterProtocol")
                        .WithMany()
                        .HasForeignKey("RepeaterProtocolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TindeqTrainer.Domain.Entities.WorkoutProtocol", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkoutProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepeaterProtocol");
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.WorkoutProtocol", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
