// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TindeqTrainer.Infrastructure.Persistence;

#nullable disable

namespace TindeqTrainer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308165042_RemoveProtocolDefault")]
    partial class RemoveProtocolDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.Protocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AudioCues")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CountdownBeeps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CountdownSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("HandSwitchSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxWeightKg")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepsPerSet")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RestSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("SetRestSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("WeightPercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("WorkSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Protocols");

                    b.HasData(
                        new
                        {
                            Id = new Guid("664101f7-7dcd-4fb4-94f5-61e7f80c6ef0"),
                            AudioCues = true,
                            CountdownBeeps = true,
                            CountdownSeconds = 5.0,
                            HandSwitchSeconds = 30.0,
                            MaxWeightKg = 0.0,
                            Name = "Max Repeaters 80%",
                            NumberOfSets = 1,
                            RepsPerSet = 6,
                            RestSeconds = 3.0,
                            SetRestSeconds = 0.0,
                            WeightPercentage = 80.0,
                            WorkSeconds = 7.0
                        },
                        new
                        {
                            Id = new Guid("2cf4e16b-c3a7-4dfa-8944-b1d6b2384f89"),
                            AudioCues = true,
                            CountdownBeeps = true,
                            CountdownSeconds = 5.0,
                            HandSwitchSeconds = 30.0,
                            MaxWeightKg = 0.0,
                            Name = "Endurance 60%",
                            NumberOfSets = 1,
                            RepsPerSet = 10,
                            RestSeconds = 3.0,
                            SetRestSeconds = 0.0,
                            WeightPercentage = 60.0,
                            WorkSeconds = 7.0
                        },
                        new
                        {
                            Id = new Guid("d53a3ea5-d9bf-43a6-8ff8-e8f7c7f07f0a"),
                            AudioCues = true,
                            CountdownBeeps = true,
                            CountdownSeconds = 5.0,
                            HandSwitchSeconds = 30.0,
                            MaxWeightKg = 0.0,
                            Name = "Short Power 90%",
                            NumberOfSets = 1,
                            RepsPerSet = 4,
                            RestSeconds = 5.0,
                            SetRestSeconds = 0.0,
                            WeightPercentage = 90.0,
                            WorkSeconds = 5.0
                        });
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AvgForceKg")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PeakForceKg")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("ProtocolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.SessionSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hand")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimestampSeconds")
                        .HasColumnType("REAL");

                    b.Property<float>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionSamples");
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.Session", b =>
                {
                    b.HasOne("TindeqTrainer.Domain.Entities.Protocol", "Protocol")
                        .WithMany()
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.SessionSample", b =>
                {
                    b.HasOne("TindeqTrainer.Domain.Entities.Session", "Session")
                        .WithMany("Samples")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TindeqTrainer.Domain.Entities.Session", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
